export enum DiagnosticImpressionCategories {
  'Trastorno de ansiedad generalizada',
  'Trastorno de ansiedad por separación',
  'Depresión infantil',
  'Estrés agudo',
  'Dependencia afectiva',
  'Bulimia',
  'Anorexia',
  'Duelo',
  'Problemas de autoestima',
  'Falta de algunas habilidades sociales',
  'Apego inseguro',
  'Labilidad emocional',
  'Desmotivación académica',
  'Trastornos del desarrollo ',
  'Autismo',
  'Dificultades específicas de aprendizaje',
  'Dificultades para la adquisición de la lectura y la escritura ',
  'Dificultades del procesamiento sensorial',
  'Trastorno por déficit de atención con hiperactividad',
  'Trastorno por déficit de atención sin hiperactividad',
  'Déficit en el procesamiento de la información',
  'Déficit en el tiempo de respuesta',
  'Trastornos del lenguaje y la comunicación',
  'Déficit intelectual',
  'Bajo rendimiento académico',
  'Trastorno negativo desafiante',
  'Falta de control de impulsos',
  'Conducta disruptiva',
  'Problemas de adaptación escolar',
  'Dificultad para seguir indicaciones',
  'Problemas familiares: resolución de conflictos y comunicación',
  'Problemas relativos al grupo primario',
  'Conflicto paterno-materno filiales',
  'Desorganización familiar por divorcio',
  OTRO = 'Otra'
}
